version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      eslint:
        patterns:
          - eslint*
          - '@typescript-eslint/*'
          - prettier
      vite:
        patterns:
          - vite*
          - '@vitejs/*'
    labels:
      - dependencies
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /web/backend
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - backend

  - package-ecosystem: npm
    directory: /web/frontend
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - frontend

  - package-ecosystem: npm
    directory: /packages/shell
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - shell

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci
